export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
